---
title: "IHW histograms"
author: "Wolfgang Huber"
date: "2024-04-15"
format:
  html:
    embed-resources: false
    page-layout: full
    toc: true
    css: wh.css
highlight-style: tango
---

```{r initialize}
#| label: init
#| echo: false
#| cache: false
## Set default options for code chunks
knitr::opts_chunk$set(cache = FALSE)
```
```{r}
#| label: loadpkgs
#| message: false
#| cache: false
library("ggplot2")
library("dplyr")
figsiz = 4
```
```{r}
hypotheses_per_group = 10000
sigma = 1
dm = c(A = 0.05, B = 0.4, C = 0.55)
ns = 10
x = lapply(names(dm), function(i) {
  m = cbind(matrix(rnorm(ns * hypotheses_per_group, mean = 0, sd = sigma), nrow = hypotheses_per_group, ncol = ns),
            matrix(rnorm(ns * hypotheses_per_group, mean = dm[i], sd = sigma), nrow = hypotheses_per_group, ncol = ns)) 
  p = genefilter::rowttests(m, fac = factor(rep(c("A", "B"), each = ns)))$p.value
  tibble(p = p, grp = i)
}) |> bind_rows()
```
```{r}
#| label: fig_hist_combined
#| fig-width: !expr figsiz
#| fig-height: !expr figsiz
#| fig-dpi: 600
#| out-width: "400px"
makehist = function(x, group, alpha = 0.05, border = "#000000", ...) {
  h = hist(x$p[x$grp %in% group], breaks = seq(0, 1, by = 0.05/3),  plot = FALSE)
  n0 = mean(h$counts[h$mids > 0.5])
  plot(h, col = "#a0a0a0", border = border, main = NULL, xlab = "p", ...)
  abline(h = n0,    col = "#d0d0d0", lwd = 3)
  wh = which(h$mids < alpha)
  for(i in wh) {
    polygon(x = h$breaks[c(i, i+1, i+1, i)], y = c(0,   0, n0,          n0), col = "#cdcd00", border = border)      
    polygon(x = h$breaks[c(i, i+1, i+1, i)], y = c(n0, n0, h$counts[i], h$counts[i]), col = "#0057b8", border = border)      
  }
  abline(v = alpha, col = "red", lwd = 3)
  c(yellow = n0*length(wh), 
    `yellow + blue` = sum(h$counts[wh]), 
    FDR = round(n0*length(wh) / sum(h$counts[wh]), 3))
}
  
makehist(x, names(dm))
```
```{r}
#| label: fig_hist_stratified
#| fig-width: !expr figsiz 
#| fig-height: !expr figsiz
#| fig-dpi: 600
#| out-width: "400px"
sapply(names(dm), function(g) makehist(x, g, ylim = c(0, 750)))
```


