---
title: "Explore the Norman data"
subtitle: "Step 2: Explore"
author: "Wolfgang Huber"
date: "2026-01-02"
format:
  html:
    embed-resources: false
    page-layout: full
    css: wh.css
    toc: true
execute:
  fig-align: center
---

# Setup

```{r}
#| label: setup
#| echo: false
#| message: false
#| warning: false
knitr::opts_chunk$set(cache = TRUE)
library("assertthat")
library("dplyr")
library("tidyr")
library("ggplot2")
```

# Load result from Step 1

```{r}
#| label: load
load("norman-perturbseq-mat.RData")
```

# Size Factors

```{r}
#| label: sizefactors1
#| fig.dim: !expr c(8, 3)
sf = DESeq2::estimateSizeFactorsForMatrix(mat)
last(colnames(mat))
ggplot(tibble(i = seq(along = sf), sf = sf), aes(x = i, y = sf)) + 
  geom_point() +
  scale_y_log10()
```
```{r}
#| label: sizefactors2
#| fig.dim: !expr c(3, 3)
ggplot(tibble(sum = colSums(mat), sf = sf), aes(x = sum, y = sf)) + 
  geom_point() +
  scale_x_log10() + scale_y_log10()
```

```{r}
#| label: normalize
nmat = mat
for(i in seq_along(sf))
  nmat[,i] = nmat[,i] / sf[i]
```

The size factors vary by about a factor of 10, which seems OK, except for the very last one. Let's check that it is sane.

```{r}
#| label: checkctrl
#| fig.dim: !expr c(10, 10)
sampledcolumns = sample(colnames(mat)[-ncol(mat)], 25)
nmat[, c(sampledcolumns, last(colnames(mat)))] |>
  as_tibble() |>
  mutate(row_id = seq_len(nrow(mat))) |>
  pivot_longer(cols = all_of(sampledcolumns), 
               names_to = "sample", 
               values_to = "value") |>
  ggplot(aes(x = asinh(ctrl), y = asinh(value))) + 
    geom_point(size = 0.1) + 
    geom_abline(slope = 1, col = "red") +
    facet_wrap(vars(sample))
```